FROM ubuntu:22.04
RUN apt-get update && apt-get install --yes --no-install-recommends git make

RUN git config --global init.defaultBranch main

LABEL description="This text illustrates \
that label-values can span multiple lines."