name: Actions
on:
  - push
jobs:
  install_project:
    runs-on: ubuntu-22.04
    container:
      image: ghcr.io/dduportal/esgi-gitpod
      options: --user=root
    steps:
      - uses: actions/checkout@v4
      - run: npm install
      - run: npm run lint