name: CI/CD Workflow

on:
  push:
    tags:
      - '*'

jobs:
  build-and-publish:
    runs-on: buntu-22.04

    steps:
      - name: "Checkout Repository"
        uses: actions/checkout@v3

      - name: "Run Linter"
        run: echo "Linting the code..."

      - name: "Build Application"
        run: echo "Building the application..."

      - name: "Run Tests"
        run: echo "Running tests..."

      - name: "Login to Docker Hub"
        uses: docker/login-action@v3
        if: startsWith(github.ref, 'refs/tags/')
        with:
          username: "dilo145"
          password: "${{ secrets.DOCKERHUB_TOKEN }}"

      - name: "Build and Push Docker Image"
        uses: docker/build-push-action@v6
        if: startsWith(github.ref, 'refs/tags/')
        with:
          push: true
          context: ./../../Dockerfiles/docker-node/Dockerfile
          tags: "dilo145/node:${{ github.ref_name }}"
